#! /bin/zsh

# register:
# fixme: unless it's already there!

add_line_to_file()
{
    local LINE=$1
    local file=$2
    if ! grep -F $LINE ${file} > /dev/null; then
        echo $LINE >> $file
    fi
}

add_line_to_file "source /usr/share/zsh/site-functions/rc.zsh" /etc/zsh/zshrc
add_line_to_file "source /etc/env" /etc/zsh/zshenv
