name: Publish Debian Package
run-name: "Publish Debian Package — ${{ github.ref_name }}"

on:
  push:
    tags:
      - 'sid/*'
      - 'unstable/*'

  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or SHA to build'
        type: string
        default: 'main'

permissions:
  contents: write
  packages: write # Optional, but good if you use GHCR

jobs:
  publish:
    uses: michal-maruska/workflows/.github/workflows/build-and-publish-deb.yml@main
    with:
      ref: ${{ inputs.ref || github.ref }}
      architectures: ${{ inputs.architectures || vars.DEFAULT_ARCHITECTURES || '["amd64"]' }}
    # xorg is a fork, so I need to store the token locally, and pass is explicitly:
    secrets: inherit
